name: Application Build Workflow

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: development
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd main
          docker build -t ecs-poc-app:latest .

      - name: Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ecs-poc-app:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-scan-results.txt"

      - name: Upload Trivy Scan Results Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: trivy-scan-results.txt
