name: Application Build Workflow

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: development
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Code Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          # output: "trivy-code-scan-results.txt"

      # - name: Upload Trivy Code Scan Results Artifact
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: trivy-code-scan-results
      #     path: trivy-code-scan-results.txt

      - name: Build Docker image
        run: |
          docker build -t ecs-poc-app:latest .

      - name: Image Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ecs-poc-app:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-image-scan-results.txt"

      - name: Upload Trivy Image Scan Results Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-image-scan-results
          path: trivy-image-scan-results.txt
